name: Wheels

on:
  workflow_dispatch:
  push:
    branches:
    - beta/*
    - master
  release:
    types: [published]

env:
  CIBW_ENVIRONMENT: "PIP_ONLY_BINARY=:all:"
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: python -m pytest {package}/tests

jobs:
  wheels:
    name: Build ${{ matrix.py }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        py: [cp36, cp37, cp38, cp39]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: joerick/cibuildwheel@v1.8.0
        env:
          CIBW_BUILD: ${{ matrix.py }}-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  sdist:
    name: Build source package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - run: python -m pip install --upgrade pip build wheel
      - run: python -m build --sdist

      - run: python -m pip install dist/iminuit-*
      - run: python -m pip install pytest
      - run: python -m pytest

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload:
    if: "github.event.release"
    needs: [wheels, sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{secrets.pypi_password}}
